# Netlify configuration for Next.js portfolio

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables
[context.production.environment]
  NEXT_PUBLIC_BASE_URL = "https://michellelimanjae.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_BASE_URL = "https://deploy-preview-$REVIEW_ID--michellelimanjae.netlify.app"

[context.branch-deploy.environment]
  NEXT_PUBLIC_BASE_URL = "https://$BRANCH--michellelimanjae.netlify.app" 